CREATE TABLE stundenwerte (
	TKNR				integer			NOT NULL,
	Zst					integer			NOT NULL,
	Land				integer			NOT NULL,
	Strklas				character(1)	NOT NULL,
	Strnum				character(10),
	Datum				date,
	Wotag				integer,
	Fahrtzw				character(1),
	Stunde				integer,
	time				TIMESTAMP,
	KFZ_R1				integer,
	K_KFZ_R1			character(1),
	KFZ_R2				integer,
	K_KFZ_R2			character(1),
	Lkw_R1				integer,
	K_Lkw_R1			character(1),
	Lkw_R2				integer,
	K_Lkw_R2			character(1),
	PLZ_R1				integer,
	K_PLZ_R1			character(1),
	Pkw_R1				integer,			
	K_Pkw_R1			character(1),
	Lfw_R1				integer,
	K_Lfw_R1			character(1),
	Mot_R1				integer,
	K_Mot_R1			character(1),
	PmA_R1				integer,
	K_PmA_R1			character(1),
	Bus_R1				integer,
	K_Bus_R1			character(1),
	LoA_R1				integer,
	K_LoA_R1			character(1),
	Lzg_R1				integer,
	K_Lzg_R1			character(1),
	Sat_R1				integer,
	K_Sat_R1			character(1),
	Son_R1				integer,
	K_Son_R1			character(1),
	PLZ_R2				integer,
	K_PLZ_R2			character(1),
	Pkw_R2				integer,
	K_Pkw_R2			character(1),
	Lfw_R2				integer,
	K_Lfw_R2			character(1),
	Mot_R2				integer,
	K_Mot_R2			character(1),
	PmA_R2				integer,
	K_PmA_R2			character(1),
	Bus_R2				integer,
	K_Bus_R2			character(1),
	LoA_R2				integer,
	K_LoA_R2			character(1),
	Lzg_R2				integer,	
	K_Lzg_R2			character(1),
	Sat_R2				integer,
	K_Sat_R2			character(1),
	Son_R2				integer,
	K_Son_R2			character(1)
);

SELECT create_hypertable('stundenwerte','time');

CREATE INDEX ON stundenwerte (zst, time DESC);