CREATE TABLE bbsr_kreise_2017 (
	krs17					character(8)				NOT NULL,
	krs17_name				character varying(250)		NOT NULL,
	fl17					numeric(12,2),
	bev17					numeric(8),
	kbez					integer,
	kbez_name				character varying(250),
	ksitz					character varying(250),
	kslk					integer,
	kslk_name				character varying(250),
	kreg17					character(8),
	kreg17_name				character varying(250),
	st_kreg					integer,
	st_kreg_name			character varying(250),
	kslk_kreg				integer,
	kslk_kreg_name			character varying(250),
	ktyp4					integer,
	ktyp4_name				character varying(250),
	slraum					integer,
	slraum_name				character varying(250),
	raumt2010				integer,
	raumt2010_name			character varying(250),
	ror11					character(4),
	ror11_name				character varying(250),
	rtyp3					integer,
	rtyp3_name				character varying(250),
	amr16					character(3),
	amr16_name				character varying(250),
	rbz						character(3),
	rbz_name				character varying(250),
	nuts2					character(4),
	nuts2_name				character varying(250),
	metropolen_IKM_2015_a	character varying(250),
	metropolen_IKM_2015_b 	character varying(250),
	land					character(2),
	land_name				character varying(250),
	wo						integer,
	wo_name					character varying(250)	
);

CREATE INDEX ON bbsr_kreise_2017 (krs17);